### ISSUE TITLE
ecs_prefect_agent.yml s3_block_name hardcoded ?

### ISSUE THREAD

**Issue by jralduaveuthey** [anna-geller/dataflow-ops#1]
in the line 123 in ecs_prefect_agent.yml` -sb s3/prod `but maybe should be` s3/${{ github.event.inputs.s3_block_name }} ` ?

**Comment by anna-geller** [comment]
Sorry for not getting back to you earlier, I didn't see this issue until now. This seems to be addressed now so I'll close the issue. Thanks so much!
