### ISSUE TITLE
Bad path in ecs_prefect_agent_flows_run_in_agent_container.yml

### ISSUE THREAD

**Issue by rosulucian** [anna-geller/dataflow-ops#10]
https://github.com/anna-geller/dataflow-ops/blob/3e0d93bd16bf7828befc49223bb34e38fc8bdee8/.github/workflows/ecs_prefect_agent_flows_run_in_agent_container.yml#L161

Works fine if path is
`template: infrastructure/ecr_repository.yml`

**Comment by anna-geller** [comment]
Correct, renamed now. thanks!
