### ISSUE TITLE
Which IAM roles does the AWS account needs to have?

### ISSUE THREAD

**Issue by christian-becker-ta** [anna-geller/dataflow-ops#12]
Hi, 
i'm currently trying to execute the pipeline and build the AWS Infrastructure for "1 Initial - ECS Prefect agent" but i get multiple times, that this and that right is missing. 

Is it possible that you can generate a file in which we can see which rights are exactly needed? This would be great and safe others lots of time :-) 

Thanks Christian

**Comment by Black-Milk** [comment]
Ditto this

**Comment by anna-geller** [comment]
sorry folks, this repo is no longer maintained. you can ask questions on https://github.com/PrefectHQ/prefect
