### ISSUE TITLE
example to use common utils

### ISSUE THREAD

**Issue by extdponomarchuk** [anna-geller/dataflow-ops#14]
Hi @anna-geller 
Could you add an example Flow which will use some util from the `dataflowops` folder?
Thanks!

**Comment by anna-geller** [comment]
Sorry, I'm no longer at Prefect and this repo is no longer maintained. 

I'm adding new flows to this repo now :) https://github.com/kestra-io/examples. Check it out if you're interested, would love to have you in that new community! https://kestra.io/slack
